spring.application.name=apidatabase

# ✅ H2 DATABASE (WORKING)
spring.datasource.username=postgres
spring.datasource.password=Sadie123

spring.datasource.url=jdbc:postgresql://localhost:5432/apidatabase
spring.h2.console.enabled=false

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ✅ H2 Console

spring.h2.console.path=/h2-console

# ✅ JWT
jwt.secret=your-very-strong-secret-key-must-be-32-chars
jwt.expiration=86400000

# ✅ SERVER
server.port=8080

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect